export const COUNTRY_NAME_MAP = {
  colombia: 'Colombia',
  brazil: 'Brazil',
  ethiopia: 'Ethiopia',
  'east java': 'Indonesia',
  rwanda: 'Rwanda',
  'costa rica': 'Costa Rica',
  kenya: 'Kenya',
  guatemala: 'Guatemala',
  'el salvador': 'El Salvador',
  peru: 'Peru',
  honduras: 'Honduras',
  india: 'India',
  indonesia: 'Indonesia',
  mexico: 'Mexico',
  burundi: 'Burundi',
  tanzania: 'Tanzania',
  panama: 'Panama',
  nicaragua: 'Nicaragua',
  bolivia: 'Bolivia',
  vietnam: 'Vietnam',
  uganda: 'Uganda',
  congo: 'Congo'
}
